set nocompatible       " Don't try to be vi compatible

let mapleader=","       " leader is comma
" jj is escape
inoremap jj <esc>

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd
" Blink cursor on error instead of beeping (grr)
set visualbell

" Colorscheme
colorscheme badwolf
syntax enable           " enable syntax processing


" Spaches & tabs
set shiftwidth=0    " set shiftwidth to use tabstop
set softtabstop=2   " number of spaces in tab when editing
set tabstop=2       " tab spaces
set expandtab       " tabs are spaces

" UI
set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

" Searching
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Folding
" set foldenable          " enable folding
" set foldlevelstart=10   " open most folds by default
" set foldnestmax=10      " 10 nested fold max
" space open/closes folds
" noremap <space> za
" set foldmethod=indent   " fold based on indent level

" Movement
" move vertically by visual line
nnoremap j gj
nnoremap k gk
" move to beginning/end of line
nnoremap B ^
nnoremap E $
" $/^ doesn't do anything
nnoremap $ <nop>
nnoremap ^ <nop>
" highlight last inserted text
" nnoremap gV `[v`]
